# Level 2 to Level 3 and 4 script
# Last edited: 11/08/2017 - Nicholas Clark

#### Description:
# This script takes "Level 2" dose-response data generated by the HMS LINCS Center
# at Harvard Medical School (cell counts along with calculated "GR values" and
# relative cell counts from individual wells) and converts it to "Level 3" data
# (the same, averaged over technical replicates from different plates).
# The level 3 data is then converted to "Level 4" data - fitted dose-response 
# curve metrics.

#### Input:
# Breast cancer density project
# Level 2: LDS-1261 or HMS dataset 20256
# http://lincsportal.ccs.miami.edu/datasets-beta/#/view/LDS-1261

#### Output:
# lvl3 - data frame of mean cell counts, "GR values", and relative cell counts
# (averaged over technical replicates)
# GRval_lvl4 - data frame of growth-rate inhibition values (analogous to relative cell count)
# for each experiment
# GRmet_lvl4 - data frame of growth-rate inhibition metrics (GR50, GRmax, etc.) as well as
# traditional dose-reponse metrics (IC50, Emax, etc.) for fitted dose-response curves.

cat("Loading required packages\n")
library(readr)
library(dplyr)
library(LINCSDataPortal)
library(GRmetrics)

cat("Downloading Level 2 dataset from LINCS Data Portal\n")
# Download Level 2 dataset
download_dataset("LDS-1261")
untar("LDS-1261.tar.gz", exdir = ".")
system("rm *tar.gz")

cat("Reading dataset into R\n")
# Read datasets into R
# Note: read_tsv function will incorrectly guess "Small Mol Concentration" as
# an integer column unless you increase the value of "guess_max"
lvl2 = read_tsv("LDS-1261/Data/20256.txt", guess_max = 55000)

## Average over technical replicates
# Simply take the mean of the cell counts and GR values for each unique
# combination of cell line, small molecule, concentration, replicate, and seeding density

cat("Averaging cell counts by each combination of cell line, small molecule, concentration, replicate, and seeding density\n")
lvl3 = lvl2 %>% group_by(`Cell HMS LINCS ID`, `Cell Name`, `Small Molecule HMS LINCS ID`,
                         `Small Molecule Name`, `Small Mol Concentration`,
                         `Small Mol Conc Unit`, Replicate, `Seeding Density`) %>%
  dplyr::summarise(
    `Mean Total Cell Count Before Treatment` = round(mean(`Total Cell Count Before Treatment`),2),
    `Mean Total Cell Count After Treatment` = round(mean(`Total Cell Count After Treatment`),2),
    `Mean Total Control Cell Count` = round(mean(`Total Control Cell Count`),2),
    `Mean Relative Cell Count` = round(mean(`Relative Cell Count`),4),
    `Mean Normalized Growth Rate Inhibition Value` = round(mean(`Normalized Growth Rate Inhibition Value`),4) ) %>%
  dplyr::filter(`Small Mol Concentration` != 0) %>%
  dplyr::arrange(`Cell Name`, `Small Molecule Name`, Replicate, `Seeding Density`,
                 `Small Mol Concentration`) %>%
  ungroup %>%
  as.data.frame()
  
if(exists("lvl3")) {cat("\nDone. The data frame 'lvl3' contains Level 3 data (averaged cell counts)\n")}
 
cat("\nRenaming data frame columns for input into R function\n")
lvl3_rename = lvl3 %>%
  dplyr::rename(cell_line = `Cell Name`,
                treatment = `Small Molecule Name`,
                concentration = `Small Mol Concentration`,
                cell_count = `Mean Total Cell Count After Treatment`,
                cell_count__time0 = `Mean Total Cell Count Before Treatment`,
                cell_count__ctrl = `Mean Total Control Cell Count`
  )

cat("\nCalculating GR values and fitted curve metrics using GRmetrics R package... This may take a minute or two.")
# Calculate GR values and fitted curve metrics
GRmet = suppressWarnings(GRfit(lvl3_rename, c("cell_line", "treatment", "Replicate", "Seeding Density")))

GRval_lvl4 = GRgetValues(GRmet)
GRmet_lvl4 = GRgetMetrics(GRmet)
if(exists("GRval_lvl4") & exists("GRmet_lvl4")) {cat("\n\nDone. Two output data frames created.\nThe data frame 'GRval_lvl4' contains GR values at each concentration.\nThe data frame 'GRmet_lvl4' contains fitted dose-response curve metrics.")}

View(lvl3)
View(GRval_lvl4)
View(GRmet_lvl4)
