# Level 3 to Level 4 script
# Last edited: 11/07/2017 - Nicholas Clark

#### Description:
# This script takes "Level 3" dose-response data generated by the HMS LINCS Center
# at Harvard Medical School (cell counts along with calculated "GR values" and
# relative cell counts, averaged over technical replicates from different plates)
# and converts it to "Level 4" data - fitted dose-response curve metrics.

#### Input:
# Breast cancer density project
# Level 3: LDS-1262 or HMS dataset 20257 (created by "Level2_to_Level3.R" script, or 
# downloaded from LINCS Data Portal)
# http://lincsportal.ccs.miami.edu/datasets-beta/#/view/LDS-1262

#### Output:
# GRval_lvl4 - data frame of growth-rate inhibition values (analogous to relative cell count)
# for each experiment
# GRmet_lvl4 - data frame of growth-rate inhibition metrics (GR50, GRmax, etc.) as well as
# traditional dose-reponse metrics (IC50, Emax, etc.) for fitted dose-response curves.

cat("Clearing the workspace")
rm(list = ls())

cat("\nLoading required packages")
library(readr)
library(dplyr)
library(LINCSDataPortal)
library(GRmetrics)

# Check if the data has been created from the last script
if(!exists("lvl3")) {
  cat("Downloading Level 3 dataset from LINCS Data Portal")
  # Download Level 3 dataset
  download_dataset("LDS-1262")
  untar("LDS-1262.tar.gz", exdir = ".")
  system("rm *tar.gz")
  
  cat("Reading dataset into R")
  # Read dataset into R
  lvl3 = read_tsv("LDS-1262/Data/20257.txt")
}

cat("Renaming data frame columns for input into R function")
lvl3_rename = lvl3 %>%
  dplyr::rename(cell_line = `Cell Name`,
                treatment = `Small Molecule Name`,
                concentration = `Small Mol Concentration`,
                cell_count = `Mean Total Cell Count After Treatment`,
                cell_count__time0 = `Mean Total Cell Count Before Treatment`,
                cell_count__ctrl = `Mean Total Control Cell Count`
                )

cat("\nCalculating GR values and fitted curve metrics using GRmetrics R package... This may take a minute or two.")
# Calculate GR values and fitted curve metrics
GRmet = suppressWarnings(GRfit(lvl3_rename, c("cell_line", "treatment", "Replicate", "Seeding Density")))

GRval_lvl4 = GRgetValues(GRmet)
GRmet_lvl4 = GRgetMetrics(GRmet)
if(exists("GRval_lvl4") & exists("GRmet_lvl4")) {cat("\n\nDone. Two output data frames created.\nThe data frame 'GRval_lvl4' contains GR values at each concentration.\nThe data frame 'GRmet_lvl4' contains fitted dose-response curve metrics.")}
View(GRval_lvl4)
View(GRmet_lvl4)
