# Level 2 to Level 3 script
# Last edited: 10/03/2017 - Nicholas Clark

#### Description:
# This script takes "Level 2" dose-response data generated by the HMS LINCS Center
# at Harvard Medical School (cell counts along with calculated "GR values" and
# relative cell counts from individual wells) and converts it to "Level 3" data
# (the same, averaged over technical replicates from different plates).

#### Input:
# Breast cancer density project
# Level 2: LDS-1261 or HMS dataset 20256
# http://lincsportal.ccs.miami.edu/datasets-beta/#/view/LDS-1261

#### Output:
# lvl3 - data frame of mean cell counts, "GR values", and relative cell counts
# (averaged over technical replicates)

cat("Clear the workspace\n")
rm(list = ls())

cat("Loading required packages\n")
library(readr)
library(dplyr)
library(LINCSDataPortal)

cat("Downloading Level 2 dataset from LINCS Data Portal\n")
# Download Level 2 dataset
download_dataset("LDS-1261")
untar("LDS-1261.tar.gz", exdir = ".")
system("rm *tar.gz")

cat("Reading dataset into R\n")
# Read datasets into R
# Note: read_tsv function will incorrectly guess "Small Mol Concentration" as
# an integer column unless you increase the value of "guess_max"
lvl2 = read_tsv("LDS-1261/Data/20256.txt", guess_max = 55000)

## Average over technical replicates
# Simply take the mean of the cell counts and GR values for each unique
# combination of cell line, small molecule, concentration, replicate, and seeding density

cat("Averaging cell counts by each combination of cell line, small molecule, concentration, replicate, and seeding density\n")
lvl3 = lvl2 %>% group_by(`Cell HMS LINCS ID`, `Cell Name`, `Small Molecule HMS LINCS ID`,
                         `Small Molecule Name`, `Small Mol Concentration`,
                         `Small Mol Conc Unit`, Replicate, `Seeding Density`) %>%
  dplyr::summarise(
    `Mean Total Cell Count Before Treatment` = round(mean(`Total Cell Count Before Treatment`),2),
    `Mean Total Cell Count After Treatment` = round(mean(`Total Cell Count After Treatment`),2),
    `Mean Total Control Cell Count` = round(mean(`Total Control Cell Count`),2),
    `Mean Relative Cell Count` = round(mean(`Relative Cell Count`),4),
    `Mean Normalized Growth Rate Inhibition Value` = round(mean(`Normalized Growth Rate Inhibition Value`),4) ) %>%
  dplyr::filter(`Small Mol Concentration` != 0) %>%
  dplyr::arrange(`Cell Name`, `Small Molecule Name`, Replicate, `Seeding Density`,
                 `Small Mol Concentration`) %>%
  ungroup %>%
  as.data.frame()
  
 if(exists("lvl3")) {cat("\nDone. The data frame 'lvl3' contains Level 3 data (averaged cell counts)")}
 View(lvl3)
